name: Release

on:
  push:
    branches: [main]

jobs:
  deploy-playstore:
    name: Build & Deploy to Play Store
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Enable Nix flakes
        run: |
          mkdir -p ~/.config/nix
          echo "experimental-features = nix-command flakes" >> ~/.config/nix/nix.conf

      - name: Prepare Keystore
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          if [ -n "$ANDROID_KEYSTORE_BASE64" ]; then
            echo "$ANDROID_KEYSTORE_BASE64" | base64 -d > android/app/upload-keystore.jks
          else
            echo "Error: ANDROID_KEYSTORE_BASE64 secret is not set."
            exit 1
          fi

      - name: Build & Deploy to Play Store
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        run: nix develop --command task deploy-android-bundle
