#!/usr/bin/env bash
# Verify that the script embedded in k8s/ci-monitor.yaml matches the
# canonical source in scripts/ci-monitor.sh. Run from a pre-commit hook
# (see .pre-commit-config.yaml) to prevent drift.
#
# Pass --write to rebuild the manifest from the script. The embedded copy
# uses a YAML literal block scalar (|) with 4-space indentation under
# `ci-monitor.sh: |`.
set -euo pipefail

ROOT=$(git rev-parse --show-toplevel)
SCRIPT="$ROOT/scripts/ci-monitor.sh"
MANIFEST="$ROOT/k8s/ci-monitor.yaml"
MARKER_START="# >>> EMBEDDED ci-monitor.sh START — generated by scripts/check_ci_monitor_sync.sh"
MARKER_END="# <<< EMBEDDED ci-monitor.sh END"

if [ ! -f "$SCRIPT" ]; then
    echo "ERROR: $SCRIPT not found"
    exit 1
fi
if [ ! -f "$MANIFEST" ]; then
    echo "ERROR: $MANIFEST not found"
    exit 1
fi

build() {
    # Emit the manifest with the script re-embedded between marker lines.
    # Blank lines are kept blank (not indented) — YAML block scalars accept
    # this and trailing-whitespace pre-commit hooks would strip them anyway.
    awk -v script="$SCRIPT" -v start="$MARKER_START" -v end="$MARKER_END" '
        BEGIN { skip = 0; indent = "    " }
        $0 ~ start {
            print
            while ((getline line < script) > 0) {
                if (length(line) == 0) {
                    print ""
                } else {
                    print indent line
                }
            }
            close(script)
            skip = 1
            next
        }
        $0 ~ end {
            print
            skip = 0
            next
        }
        skip == 0 { print }
    ' "$MANIFEST"
}

if [ "${1:-}" = "--write" ]; then
    tmp=$(mktemp)
    build > "$tmp"
    mv "$tmp" "$MANIFEST"
    echo "Rebuilt $MANIFEST from $SCRIPT"
    exit 0
fi

if ! diff -q <(build) "$MANIFEST" >/dev/null; then
    echo "ERROR: k8s/ci-monitor.yaml is out of sync with scripts/ci-monitor.sh."
    echo "Run: scripts/check_ci_monitor_sync.sh --write"
    diff <(build) "$MANIFEST" || true
    exit 1
fi
