#!/usr/bin/env python3
"""Tests for check_android_registrant.py — the guard that keeps
GeneratedPluginRegistrant.java in sync with pubspec.lock (issues #531, #539)."""

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

import check_android_registrant as car


def _block(pub_name: str, java_class: str) -> str:
    """Render a registration block like the Flutter tool generates."""
    return (
        "    try {\n"
        f"      flutterEngine.getPlugins().add(new {java_class}());\n"
        "    } catch (Exception e) {\n"
        f'      Log.e(TAG, "Error registering plugin {pub_name}, {java_class}", e);\n'
        "    }\n"
    )


def _registrant(*blocks: str) -> str:
    return (
        "package io.flutter.plugins;\n"
        "public final class GeneratedPluginRegistrant {\n"
        "  public static void registerWith(FlutterEngine flutterEngine) {\n"
        + "".join(blocks)
        + "  }\n}\n"
    )


_LOCK = (
    "# Generated by pub\n"
    "packages:\n"
    "  connectivity_plus:\n"
    "    dependency: \"direct main\"\n"
    "    source: hosted\n"
    "    version: \"1.0.0\"\n"
    "  path_provider_android:\n"
    "    dependency: transitive\n"
    "    source: hosted\n"
    "    version: \"2.0.0\"\n"
    "sdks:\n"
    "  dart: \">=3.0.0 <4.0.0\"\n"
)


class RegisteredPluginsTests(unittest.TestCase):
    def test_extracts_pub_names_from_error_lines(self):
        text = _registrant(
            _block("connectivity_plus",
                   "dev.fluttercommunity.plus.connectivity.ConnectivityPlugin"),
            _block("path_provider_android",
                   "io.flutter.plugins.pathprovider.PathProviderPlugin"),
        )
        self.assertEqual(
            car.registered_plugins(text),
            ["connectivity_plus", "path_provider_android"],
        )

    def test_no_registrations(self):
        self.assertEqual(car.registered_plugins("class X {}"), [])


class LockedPackagesTests(unittest.TestCase):
    def test_parses_two_space_indented_keys(self):
        self.assertEqual(
            car.locked_packages(_LOCK),
            {"connectivity_plus", "path_provider_android"},
        )

    def test_ignores_nested_and_sdk_keys(self):
        packages = car.locked_packages(_LOCK)
        self.assertNotIn("dependency", packages)
        self.assertNotIn("dart", packages)


class FindStaleTests(unittest.TestCase):
    def test_all_registered_plugins_present(self):
        text = _registrant(
            _block("connectivity_plus", "a.b.C"),
            _block("path_provider_android", "d.e.F"),
        )
        self.assertEqual(car.find_stale(text, _LOCK), [])

    def test_detects_removed_plugin(self):
        # Mirrors #531/#539: sqlcipher_flutter_libs dropped from deps but still
        # registered in the committed registrant.
        text = _registrant(
            _block("connectivity_plus", "a.b.C"),
            _block("sqlcipher_flutter_libs",
                   "eu.simonbinder.sqlite3_flutter_libs.Sqlite3FlutterLibsPlugin"),
        )
        self.assertEqual(car.find_stale(text, _LOCK), ["sqlcipher_flutter_libs"])


if __name__ == "__main__":
    unittest.main()
