baseURL = 'https://sharedinbox.de/'
languageCode = 'en-us'
title = 'SharedInbox'
theme = 'PaperMod'

[params]
    env = 'production'
    title = 'SharedInbox'
    description = 'IMAP/SMTP Email Client'
    author = 'SharedInbox Team'

    [params.homeInfoParams]
        Title = "SharedInbox"
        Content = "The modern IMAP/SMTP email client for your desktop and mobile."

    [[params.socialIcons]]
        name = "codeberg"
        url = "https://codeberg.org/guettli/sharedinbox"

[[menu.main]]
    name = "Builds"
    url = "/builds/"
    weight = 5

[[menu.main]]
    name = "Privacy Policy"
    url = "/privacy/"
    weight = 10
