// Mocks generated by Mockito 5.4.6 from annotations
// in sharedinbox/test/unit/account_sync_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:sharedinbox/core/filter/filter_expression.dart' as _i10;
import 'package:sharedinbox/core/models/account.dart' as _i6;
import 'package:sharedinbox/core/models/email.dart' as _i3;
import 'package:sharedinbox/core/models/mailbox.dart' as _i2;
import 'package:sharedinbox/core/models/pending_change.dart' as _i11;
import 'package:sharedinbox/core/repositories/account_repository.dart' as _i4;
import 'package:sharedinbox/core/repositories/email_repository.dart' as _i9;
import 'package:sharedinbox/core/repositories/mailbox_repository.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeMailbox_0 extends _i1.SmartFake implements _i2.Mailbox {
  _FakeMailbox_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEmailBody_1 extends _i1.SmartFake implements _i3.EmailBody {
  _FakeEmailBody_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSyncEmailsResult_2 extends _i1.SmartFake
    implements _i3.SyncEmailsResult {
  _FakeSyncEmailsResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReliabilityResult_3 extends _i1.SmartFake
    implements _i3.ReliabilityResult {
  _FakeReliabilityResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMailboxDiagnostics_4 extends _i1.SmartFake
    implements _i3.MailboxDiagnostics {
  _FakeMailboxDiagnostics_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AccountRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountRepository extends _i1.Mock implements _i4.AccountRepository {
  MockAccountRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i6.Account>> observeAccounts() => (super.noSuchMethod(
        Invocation.method(
          #observeAccounts,
          [],
        ),
        returnValue: _i5.Stream<List<_i6.Account>>.empty(),
      ) as _i5.Stream<List<_i6.Account>>);

  @override
  _i5.Future<_i6.Account?> getAccount(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getAccount,
          [id],
        ),
        returnValue: _i5.Future<_i6.Account?>.value(),
      ) as _i5.Future<_i6.Account?>);

  @override
  _i5.Future<void> addAccount(
    _i6.Account? account,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAccount,
          [
            account,
            password,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> updateAccount(
    _i6.Account? account, {
    String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAccount,
          [account],
          {#password: password},
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> removeAccount(String? id) => (super.noSuchMethod(
        Invocation.method(
          #removeAccount,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String> getPassword(String? accountId) => (super.noSuchMethod(
        Invocation.method(
          #getPassword,
          [accountId],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getPassword,
            [accountId],
          ),
        )),
      ) as _i5.Future<String>);
}

/// A class which mocks [MailboxRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMailboxRepository extends _i1.Mock implements _i8.MailboxRepository {
  MockMailboxRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i2.Mailbox>> observeMailboxes(String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #observeMailboxes,
          [accountId],
        ),
        returnValue: _i5.Stream<List<_i2.Mailbox>>.empty(),
      ) as _i5.Stream<List<_i2.Mailbox>>);

  @override
  _i5.Future<int> syncMailboxes(String? accountId) => (super.noSuchMethod(
        Invocation.method(
          #syncMailboxes,
          [accountId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<_i2.Mailbox?> findMailboxByRole(
    String? accountId,
    String? role,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findMailboxByRole,
          [
            accountId,
            role,
          ],
        ),
        returnValue: _i5.Future<_i2.Mailbox?>.value(),
      ) as _i5.Future<_i2.Mailbox?>);

  @override
  _i5.Future<void> clearForResync(String? accountId) => (super.noSuchMethod(
        Invocation.method(
          #clearForResync,
          [accountId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Mailbox> createMailboxWithRole(
    String? accountId,
    String? name,
    String? role, {
    String? parentDisplayPath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMailboxWithRole,
          [
            accountId,
            name,
            role,
          ],
          {#parentDisplayPath: parentDisplayPath},
        ),
        returnValue: _i5.Future<_i2.Mailbox>.value(_FakeMailbox_0(
          this,
          Invocation.method(
            #createMailboxWithRole,
            [
              accountId,
              name,
              role,
            ],
            {#parentDisplayPath: parentDisplayPath},
          ),
        )),
      ) as _i5.Future<_i2.Mailbox>);

  @override
  _i5.Future<_i2.Mailbox> createMailbox(
    String? accountId,
    String? name, {
    String? parentDisplayPath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMailbox,
          [
            accountId,
            name,
          ],
          {#parentDisplayPath: parentDisplayPath},
        ),
        returnValue: _i5.Future<_i2.Mailbox>.value(_FakeMailbox_0(
          this,
          Invocation.method(
            #createMailbox,
            [
              accountId,
              name,
            ],
            {#parentDisplayPath: parentDisplayPath},
          ),
        )),
      ) as _i5.Future<_i2.Mailbox>);

  @override
  _i5.Future<_i2.Mailbox> renameMailbox(
    String? accountId,
    String? mailboxPath,
    String? newName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #renameMailbox,
          [
            accountId,
            mailboxPath,
            newName,
          ],
        ),
        returnValue: _i5.Future<_i2.Mailbox>.value(_FakeMailbox_0(
          this,
          Invocation.method(
            #renameMailbox,
            [
              accountId,
              mailboxPath,
              newName,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Mailbox>);

  @override
  _i5.Future<void> deleteMailbox(
    String? accountId,
    String? mailboxPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMailbox,
          [
            accountId,
            mailboxPath,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Mailbox> moveMailbox(
    String? accountId,
    String? mailboxPath, {
    required String? newParentDisplayPath,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveMailbox,
          [
            accountId,
            mailboxPath,
          ],
          {#newParentDisplayPath: newParentDisplayPath},
        ),
        returnValue: _i5.Future<_i2.Mailbox>.value(_FakeMailbox_0(
          this,
          Invocation.method(
            #moveMailbox,
            [
              accountId,
              mailboxPath,
            ],
            {#newParentDisplayPath: newParentDisplayPath},
          ),
        )),
      ) as _i5.Future<_i2.Mailbox>);
}

/// A class which mocks [EmailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmailRepository extends _i1.Mock implements _i9.EmailRepository {
  MockEmailRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<String> get onChangesQueued => (super.noSuchMethod(
        Invocation.getter(#onChangesQueued),
        returnValue: _i5.Stream<String>.empty(),
      ) as _i5.Stream<String>);

  @override
  _i5.Stream<List<_i3.Email>> observeEmails(
    String? accountId,
    String? mailboxPath, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #observeEmails,
          [
            accountId,
            mailboxPath,
          ],
          {#limit: limit},
        ),
        returnValue: _i5.Stream<List<_i3.Email>>.empty(),
      ) as _i5.Stream<List<_i3.Email>>);

  @override
  _i5.Stream<List<_i3.EmailThread>> observeThreads(
    String? accountId,
    String? mailboxPath, {
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #observeThreads,
          [
            accountId,
            mailboxPath,
          ],
          {#limit: limit},
        ),
        returnValue: _i5.Stream<List<_i3.EmailThread>>.empty(),
      ) as _i5.Stream<List<_i3.EmailThread>>);

  @override
  _i5.Stream<List<_i3.EmailThread>> observeAllInboxThreads({int? limit = 50}) =>
      (super.noSuchMethod(
        Invocation.method(
          #observeAllInboxThreads,
          [],
          {#limit: limit},
        ),
        returnValue: _i5.Stream<List<_i3.EmailThread>>.empty(),
      ) as _i5.Stream<List<_i3.EmailThread>>);

  @override
  _i5.Stream<List<_i3.Email>> observeEmailsInThread(
    String? accountId,
    String? mailboxPath,
    String? threadId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #observeEmailsInThread,
          [
            accountId,
            mailboxPath,
            threadId,
          ],
        ),
        returnValue: _i5.Stream<List<_i3.Email>>.empty(),
      ) as _i5.Stream<List<_i3.Email>>);

  @override
  _i5.Future<_i3.Email?> getEmail(String? emailId) => (super.noSuchMethod(
        Invocation.method(
          #getEmail,
          [emailId],
        ),
        returnValue: _i5.Future<_i3.Email?>.value(),
      ) as _i5.Future<_i3.Email?>);

  @override
  _i5.Future<_i3.EmailBody> getEmailBody(
    String? emailId, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEmailBody,
          [emailId],
          {#forceRefresh: forceRefresh},
        ),
        returnValue: _i5.Future<_i3.EmailBody>.value(_FakeEmailBody_1(
          this,
          Invocation.method(
            #getEmailBody,
            [emailId],
            {#forceRefresh: forceRefresh},
          ),
        )),
      ) as _i5.Future<_i3.EmailBody>);

  @override
  _i5.Future<_i3.SyncEmailsResult> syncEmails(
    String? accountId,
    String? mailboxPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #syncEmails,
          [
            accountId,
            mailboxPath,
          ],
        ),
        returnValue:
            _i5.Future<_i3.SyncEmailsResult>.value(_FakeSyncEmailsResult_2(
          this,
          Invocation.method(
            #syncEmails,
            [
              accountId,
              mailboxPath,
            ],
          ),
        )),
      ) as _i5.Future<_i3.SyncEmailsResult>);

  @override
  _i5.Future<void> setFlag(
    String? emailId, {
    bool? seen,
    bool? flagged,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #setFlag,
          [emailId],
          {
            #seen: seen,
            #flagged: flagged,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> markAllAsRead(
    String? accountId,
    String? mailboxPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAllAsRead,
          [
            accountId,
            mailboxPath,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> moveEmail(
    String? emailId,
    String? destMailboxPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveEmail,
          [
            emailId,
            destMailboxPath,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<String?> deleteEmail(String? emailId) => (super.noSuchMethod(
        Invocation.method(
          #deleteEmail,
          [emailId],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);

  @override
  _i5.Future<void> sendEmail(
    String? accountId,
    _i3.EmailDraft? draft,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmail,
          [
            accountId,
            draft,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> enqueueSend(
    String? accountId,
    _i3.EmailDraft? draft,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #enqueueSend,
          [
            accountId,
            draft,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> flushOutbox(
    String? accountId,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #flushOutbox,
          [
            accountId,
            password,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<String> downloadAttachment(
    String? emailId,
    _i3.EmailAttachment? attachment,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadAttachment,
          [
            emailId,
            attachment,
          ],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #downloadAttachment,
            [
              emailId,
              attachment,
            ],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> fetchRawRfc822(String? emailId) => (super.noSuchMethod(
        Invocation.method(
          #fetchRawRfc822,
          [emailId],
        ),
        returnValue: _i5.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #fetchRawRfc822,
            [emailId],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<List<_i3.Email>> searchEmails(
    String? accountId,
    String? mailboxPath,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEmails,
          [
            accountId,
            mailboxPath,
            query,
          ],
        ),
        returnValue: _i5.Future<List<_i3.Email>>.value(<_i3.Email>[]),
      ) as _i5.Future<List<_i3.Email>>);

  @override
  _i5.Future<List<_i3.Email>> searchEmailsGlobal(
    String? accountId,
    String? query,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEmailsGlobal,
          [
            accountId,
            query,
          ],
        ),
        returnValue: _i5.Future<List<_i3.Email>>.value(<_i3.Email>[]),
      ) as _i5.Future<List<_i3.Email>>);

  @override
  _i5.Future<List<_i3.Email>> searchEmailsStructured(
    String? accountId,
    _i10.FilterGroup? filter,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchEmailsStructured,
          [
            accountId,
            filter,
          ],
        ),
        returnValue: _i5.Future<List<_i3.Email>>.value(<_i3.Email>[]),
      ) as _i5.Future<List<_i3.Email>>);

  @override
  _i5.Future<List<_i3.Email>> getEmailsByAddress(
    String? accountId,
    String? address,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEmailsByAddress,
          [
            accountId,
            address,
          ],
        ),
        returnValue: _i5.Future<List<_i3.Email>>.value(<_i3.Email>[]),
      ) as _i5.Future<List<_i3.Email>>);

  @override
  _i5.Future<List<_i3.EmailAddress>> searchAddresses(
    String? accountId,
    String? query, {
    int? limit = 10,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchAddresses,
          [
            accountId,
            query,
          ],
          {#limit: limit},
        ),
        returnValue:
            _i5.Future<List<_i3.EmailAddress>>.value(<_i3.EmailAddress>[]),
      ) as _i5.Future<List<_i3.EmailAddress>>);

  @override
  _i5.Future<int> flushPendingChanges(
    String? accountId,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #flushPendingChanges,
          [
            accountId,
            password,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Stream<List<_i3.FailedMutation>> observeFailedMutations(
          String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #observeFailedMutations,
          [accountId],
        ),
        returnValue: _i5.Stream<List<_i3.FailedMutation>>.empty(),
      ) as _i5.Stream<List<_i3.FailedMutation>>);

  @override
  _i5.Stream<List<_i11.PendingChange>> observePendingChanges(
          String? accountId) =>
      (super.noSuchMethod(
        Invocation.method(
          #observePendingChanges,
          [accountId],
        ),
        returnValue: _i5.Stream<List<_i11.PendingChange>>.empty(),
      ) as _i5.Stream<List<_i11.PendingChange>>);

  @override
  _i5.Stream<List<_i11.PendingChange>> observeAllPendingChanges() =>
      (super.noSuchMethod(
        Invocation.method(
          #observeAllPendingChanges,
          [],
        ),
        returnValue: _i5.Stream<List<_i11.PendingChange>>.empty(),
      ) as _i5.Stream<List<_i11.PendingChange>>);

  @override
  _i5.Future<void> discardMutation(int? id) => (super.noSuchMethod(
        Invocation.method(
          #discardMutation,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> retryMutation(int? id) => (super.noSuchMethod(
        Invocation.method(
          #retryMutation,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<bool> cancelPendingChange(
    String? emailId,
    String? changeType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelPendingChange,
          [
            emailId,
            changeType,
          ],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);

  @override
  _i5.Future<void> snoozeEmail(
    String? emailId,
    DateTime? until,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #snoozeEmail,
          [
            emailId,
            until,
          ],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<int> wakeUpEmails(String? accountId) => (super.noSuchMethod(
        Invocation.method(
          #wakeUpEmails,
          [accountId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<void> restoreEmails(List<_i3.Email>? emails) =>
      (super.noSuchMethod(
        Invocation.method(
          #restoreEmails,
          [emails],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i3.Email?> findEmailByMessageId(
    String? accountId,
    String? messageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #findEmailByMessageId,
          [
            accountId,
            messageId,
          ],
        ),
        returnValue: _i5.Future<_i3.Email?>.value(),
      ) as _i5.Future<_i3.Email?>);

  @override
  _i5.Future<int> applySieveRules(String? accountId) => (super.noSuchMethod(
        Invocation.method(
          #applySieveRules,
          [accountId],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> previewSieveRuleMatches(
    String? accountId,
    String? scriptContent,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #previewSieveRuleMatches,
          [
            accountId,
            scriptContent,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Future<int> applySieveScriptToInbox(
    String? accountId,
    String? scriptContent,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #applySieveScriptToInbox,
          [
            accountId,
            scriptContent,
          ],
        ),
        returnValue: _i5.Future<int>.value(0),
      ) as _i5.Future<int>);

  @override
  _i5.Stream<void> watchJmapPush(
    String? accountId,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchJmapPush,
          [
            accountId,
            password,
          ],
        ),
        returnValue: _i5.Stream<void>.empty(),
      ) as _i5.Stream<void>);

  @override
  _i5.Future<_i3.ReliabilityResult> verifySyncReliability(
    String? accountId,
    String? mailboxPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifySyncReliability,
          [
            accountId,
            mailboxPath,
          ],
        ),
        returnValue:
            _i5.Future<_i3.ReliabilityResult>.value(_FakeReliabilityResult_3(
          this,
          Invocation.method(
            #verifySyncReliability,
            [
              accountId,
              mailboxPath,
            ],
          ),
        )),
      ) as _i5.Future<_i3.ReliabilityResult>);

  @override
  _i5.Future<_i3.MailboxDiagnostics> diagnoseMailbox(
    String? accountId,
    String? mailboxPath,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #diagnoseMailbox,
          [
            accountId,
            mailboxPath,
          ],
        ),
        returnValue:
            _i5.Future<_i3.MailboxDiagnostics>.value(_FakeMailboxDiagnostics_4(
          this,
          Invocation.method(
            #diagnoseMailbox,
            [
              accountId,
              mailboxPath,
            ],
          ),
        )),
      ) as _i5.Future<_i3.MailboxDiagnostics>);

  @override
  _i5.Future<void> clearForResync(String? accountId) => (super.noSuchMethod(
        Invocation.method(
          #clearForResync,
          [accountId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
