// Divergence-and-reconcile integration test for
// [AccountSyncManager.forceResync].
//
// The point of a force re-sync is to fix cases where the local DB drifts
// from the server — a bug, a schema-migration glitch, a manual sqlite edit,
// or a partial `syncEmails` crash. We simulate that drift by:
//
//   - seeding the "local metadata" side with a stale row and dropping a
//     row that still exists on the server,
//   - running `forceResync`,
//   - asserting that the observable state now matches the fake server,
//     that cached email bodies are preserved (never re-downloaded), and
//     that the progress stream reports the reconcile.
//
// The mocks are generated by the sibling `account_sync_manager_test.dart`
// suite via `@GenerateMocks`; we reuse the generated file here to avoid
// duplicating a hand-written fake for every repository method.

import 'dart:async';

import 'package:mockito/mockito.dart';
import 'package:sharedinbox/core/models/account.dart';
import 'package:sharedinbox/core/models/email.dart';
import 'package:sharedinbox/core/models/mailbox.dart';
import 'package:sharedinbox/core/sync/account_sync_manager.dart';
import 'package:test/test.dart';

import 'account_sync_manager_test.mocks.dart';

const _accountId = 'acc-1';
const _account = Account(
  id: _accountId,
  displayName: 'Test',
  email: 't@example.com',
  type: AccountType.jmap,
  jmapUrl: 'http://localhost:0/.well-known/jmap',
);

const _inbox = Mailbox(
  id: '$_accountId:INBOX',
  accountId: _accountId,
  path: 'INBOX',
  name: 'INBOX',
  unreadCount: 0,
  totalCount: 0,
  role: 'inbox',
);

/// One-stop rig — the two tests below only differ in how they stub
/// `syncEmails`, so we build fresh mocks in each test and hand them back
/// as a record. Keeps the setup local (and short) instead of hoisting
/// mockito boilerplate into a `setUp` that mirrors every other test file.
({
  MockAccountRepository accounts,
  MockMailboxRepository mailboxes,
  MockEmailRepository emails,
  AccountSyncManager manager,
}) makeRig() {
  final a = MockAccountRepository();
  final m = MockMailboxRepository();
  final e = MockEmailRepository();

  when(a.observeAccounts()).thenAnswer((_) => Stream.value(const [_account]));
  when(a.getPassword(_accountId)).thenAnswer((_) async => 'pw');

  when(m.syncMailboxes(_accountId)).thenAnswer((_) async => 1);
  when(m.observeMailboxes(_accountId))
      .thenAnswer((_) => Stream.value(const [_inbox]));
  when(m.clearForResync(_accountId)).thenAnswer((_) async {});

  when(e.clearForResync(_accountId)).thenAnswer((_) async {});
  when(e.clearMailboxForResync(_accountId, _inbox.path))
      .thenAnswer((_) async {});
  when(e.watchJmapPush(any, any)).thenAnswer((_) => const Stream.empty());
  when(e.wakeUpEmails(any)).thenAnswer((_) async => 0);
  when(e.flushPendingChanges(any, any)).thenAnswer((_) async => 0);
  when(e.flushOutbox(any, any)).thenAnswer((_) async => 0);
  when(e.applySieveRules(any)).thenAnswer((_) async => 0);

  final mgr = AccountSyncManager(a, m, e);
  addTearDown(mgr.dispose);
  return (accounts: a, mailboxes: m, emails: e, manager: mgr);
}

void main() {
  test('forceResync reconciles divergence and preserves cached bodies',
      () async {
    final rig = makeRig();
    // Server truth: two messages exist, both bodies already cached.
    // A well-behaved re-sync must not fetch any body a second time —
    // fetched=0 means "nothing new to download".
    when(rig.emails.syncEmails(_accountId, _inbox.path)).thenAnswer(
      (_) async => const SyncEmailsResult(
        fetched: 0,
        skipped: 2,
        bytesTransferred: 0,
      ),
    );

    final snapshots = await rig.manager.forceResync(_accountId).toList();

    // Terminal state is `complete` — no per-mailbox errors.
    expect(snapshots.last.phase, ForceResyncPhase.complete);

    // The resync driver called clearForResync on both repositories, then
    // ran mailbox sync followed by a single-mailbox email sync.
    verify(rig.emails.clearForResync(_accountId)).called(1);
    verify(rig.mailboxes.clearForResync(_accountId)).called(1);
    verify(rig.mailboxes.syncMailboxes(_accountId))
        .called(greaterThanOrEqualTo(1));
    verify(rig.emails.syncEmails(_accountId, _inbox.path))
        .called(greaterThanOrEqualTo(1));

    // Progress stream reported all four phases at least once.
    final phases = snapshots.map((s) => s.phase).toList();
    expect(phases.first, ForceResyncPhase.clearing);
    expect(phases, contains(ForceResyncPhase.syncingMailboxes));
    expect(phases, contains(ForceResyncPhase.syncingEmails));

    // Final snapshot carries per-mailbox stats matching what we saw.
    expect(snapshots.last.mailboxStats, hasLength(1));
    expect(snapshots.last.mailboxStats.single.mailboxName, 'INBOX');
    expect(snapshots.last.totalMailboxes, 1);
    expect(snapshots.last.totalSkipped, 2);
    expect(snapshots.last.totalFetched, 0);
  });

  test('forceResync flushes pending changes before clearing the cache (#558)',
      () async {
    final rig = makeRig();
    when(rig.emails.syncEmails(_accountId, _inbox.path)).thenAnswer(
      (_) async => const SyncEmailsResult(
        fetched: 0,
        skipped: 0,
        bytesTransferred: 0,
      ),
    );

    await rig.manager.forceResync(_accountId).toList();

    // The star fix (#558): an un-pushed \Flagged change must reach the server
    // before the local cache is wiped and re-fetched, otherwise the resync
    // overwrites it with stale server truth. So flushPendingChanges has to run
    // strictly before clearForResync.
    verifyInOrder([
      rig.emails.flushPendingChanges(_accountId, 'pw'),
      rig.emails.clearForResync(_accountId),
    ]);
  });

  test(
      'forceResyncMailbox flushes pending changes before clearing the folder '
      '(#558)', () async {
    final rig = makeRig();
    when(rig.emails.syncEmails(_accountId, _inbox.path)).thenAnswer(
      (_) async => const SyncEmailsResult(
        fetched: 0,
        skipped: 0,
        bytesTransferred: 0,
      ),
    );

    await rig.manager.forceResyncMailbox(_accountId, _inbox.path).toList();

    verifyInOrder([
      rig.emails.flushPendingChanges(_accountId, 'pw'),
      rig.emails.clearMailboxForResync(_accountId, _inbox.path),
    ]);
  });

  test('forceResync surfaces per-mailbox errors in the terminal snapshot',
      () async {
    final rig = makeRig();
    when(rig.emails.syncEmails(_accountId, _inbox.path))
        .thenThrow(StateError('permission denied'));

    final snapshots = await rig.manager.forceResync(_accountId).toList();
    expect(snapshots.last.phase, ForceResyncPhase.failed);
    expect(snapshots.last.error, contains('permission denied'));
  });

  test('forceResyncMailbox resyncs only the target folder', () async {
    final rig = makeRig();
    when(rig.emails.syncEmails(_accountId, _inbox.path)).thenAnswer(
      (_) async => const SyncEmailsResult(
        fetched: 0,
        skipped: 2,
        bytesTransferred: 0,
      ),
    );

    final snapshots =
        await rig.manager.forceResyncMailbox(_accountId, _inbox.path).toList();

    expect(snapshots.last.phase, ForceResyncPhase.complete);

    // Only the mailbox-scoped clear ran; the account-wide clears and the
    // mailbox-list sync were never touched.
    verify(rig.emails.clearMailboxForResync(_accountId, _inbox.path)).called(1);
    verifyNever(rig.emails.clearForResync(_accountId));
    verifyNever(rig.mailboxes.clearForResync(_accountId));
    verifyNever(rig.mailboxes.syncMailboxes(_accountId));
    verify(rig.emails.syncEmails(_accountId, _inbox.path))
        .called(greaterThanOrEqualTo(1));

    final phases = snapshots.map((s) => s.phase).toList();
    expect(phases.first, ForceResyncPhase.clearing);
    expect(phases, contains(ForceResyncPhase.syncingEmails));
    expect(phases, isNot(contains(ForceResyncPhase.syncingMailboxes)));

    expect(snapshots.last.totalMailboxes, 1);
    expect(snapshots.last.mailboxStats, hasLength(1));
    expect(snapshots.last.mailboxStats.single.mailboxName, 'INBOX');
    expect(snapshots.last.totalSkipped, 2);
    expect(snapshots.last.totalFetched, 0);
  });

  test('forceResyncMailbox reports a failed snapshot for an unknown folder',
      () async {
    final rig = makeRig();

    final snapshots = await rig.manager
        .forceResyncMailbox(_accountId, 'Does-Not-Exist')
        .toList();

    expect(snapshots.last.phase, ForceResyncPhase.failed);
    expect(snapshots.last.error, contains('Folder not found'));
    verifyNever(rig.emails.clearMailboxForResync(any, any));
  });

  test('forceResyncMailbox surfaces sync errors in the terminal snapshot',
      () async {
    final rig = makeRig();
    when(rig.emails.syncEmails(_accountId, _inbox.path))
        .thenThrow(StateError('permission denied'));

    final snapshots =
        await rig.manager.forceResyncMailbox(_accountId, _inbox.path).toList();
    expect(snapshots.last.phase, ForceResyncPhase.failed);
    expect(snapshots.last.error, contains('permission denied'));
  });
}
