name: Chaos Monkey

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  chaos-monkey-backend:
    name: Chaos Monkey (backend)
    runs-on: sharedinbox-arc
    timeout-minutes: 60
    if: github.server_url == 'https://github.com'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Dagger Remote Engine
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: scripts/setup_dagger_remote.sh
      - name: Run backend chaos monkey
        run: task chaos-monkey-backend
